version: '3'

services:
    workspace:
        image: base-workspace
        volumes:
            - "${PROJECT_DIR}:/var/www/fileserver"
        ports:
            - "8080:8080"
        tty: true
    web:
        image: base-nginx
        volumes:
            - "./fileserver.conf:/etc/nginx/conf.d/default.conf"
            - "${PROJECT_DIR}:/var/www/fileserver"
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=fileserver.local
        command: ['nginx', '-g', 'daemon off;']
        restart: always
        depends_on:
            - php
    php:
        image: base-php-full
        restart: always
        volumes:
            - "${PROJECT_DIR}:/var/www/fileserver"
